---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: school
  template:
    metadata:
      labels:
        app: school
    spec:
      containers:
      - name: cont-1
        image: siva1304/root_kids_school:latest
        ports:
        - containerPort: 80   # Use port 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: school
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deploy
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
